#!/bin/python3
import sys

t = int(input().strip())
for a0 in range(t):
    n,k = input().strip().split(' ')
    n,k = [int(n),int(k)]

    #max = 0
    #for outerloop in range(1,n):
    #    for innerloop in range(outerloop+1,n+1):
    #        binaryand = outerloop & innerloop
    #        print("A={}, B={}; A & B = {} Max={}".format(outerloop, innerloop, binaryand, max))
    #        if binaryand > max and binaryand < k:
    #            max = binaryand
    #print(max)            
    
    a=k-1
    b=(~a) & -(~a)
    if ( ( a|b) > n):
        print(a-1)
    else:
        print(a)
