#!/bin/python3

import sys
import re

names=[]
N = int(input().strip())
for a0 in range(N):
    firstName,emailID = input().strip().split(' ')
    firstName,emailID = [str(firstName),str(emailID)]
    
    fn = re.compile("[a-z]{1,20}")
    ei = re.compile("[a-z.]{1,40}@gmail.com")
    
    if fn.match(firstName) and ei.match(emailID):
        names.append(firstName)
        
names.sort()
print('\n'.join(names))
