#!/bin/python3
import sys    

n = int(sys.stdin.readline().strip())
phonebook={}
for entries in range(n):
    line=sys.stdin.readline().strip()
    (key,value)=line.split(' ')
    phonebook[key] = int(value)

for line in sys.stdin.readlines():
    name=line.strip()
    number=phonebook.get(name, 'NotInThePhoneBook')
    if number == 'NotInThePhoneBook':
        print('Not found')
    else:
        print("{}={}".format(name,number))
